In [1]:
#import dependencies
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#load and view United States Human development indicator
file = pd.read_csv("United States.csv")
#Human Development index
USA_df = pd.DataFrame(file)
USA_df

                                                   United States
Life expectancy at birth (years)                            78.9
 Age-standardized mortality rate attributed to ...         353.5
Age-standardized mortality rate attributed to n...         492.3
Child malnutrition, stunting (moderate or sever...           3.5
Current health expenditure (% of GDP)                       17.1
...                                                          ...
Population using safely managed sanitation serv...            90
Ratio of education and health expenditure to mi...           6.2
Research and development expenditure (% of GDP)              2.8
Rural population with access to electricity (%)            100.0
Total debt service (% of exports of goods, serv...          n.a.

[172 rows x 1 columns]

In [3]:
USA_df.columns = ['United_States']
USA_df

                                                   United_States
Life expectancy at birth (years)                            78.9
 Age-standardized mortality rate attributed to ...         353.5
Age-standardized mortality rate attributed to n...         492.3
Child malnutrition, stunting (moderate or sever...           3.5
Current health expenditure (% of GDP)                       17.1
...                                                          ...
Population using safely managed sanitation serv...            90
Ratio of education and health expenditure to mi...           6.2
Research and development expenditure (% of GDP)              2.8
Rural population with access to electricity (%)            100.0
Total debt service (% of exports of goods, serv...          n.a.

[172 rows x 1 columns]

In [4]:
USA_df.value_counts()

United_States
n.a.             32
100.0             2
13.4              2
2.8               2
5.0               2
                 ..
14                1
139               1
13.8              1
13.5              1
27.1              1
Length: 130, dtype: int64

In [5]:
USA_df['United_States'] = USA_df['United_States'].replace(to_replace='NaN', value='none')
USA_df

                                                   United_States
Life expectancy at birth (years)                            78.9
 Age-standardized mortality rate attributed to ...         353.5
Age-standardized mortality rate attributed to n...         492.3
Child malnutrition, stunting (moderate or sever...           3.5
Current health expenditure (% of GDP)                       17.1
...                                                          ...
Population using safely managed sanitation serv...            90
Ratio of education and health expenditure to mi...           6.2
Research and development expenditure (% of GDP)              2.8
Rural population with access to electricity (%)            100.0
Total debt service (% of exports of goods, serv...          n.a.

[172 rows x 1 columns]

In [6]:
USA_df.head(61)

                                                   United_States
Life expectancy at birth (years)                            78.9
 Age-standardized mortality rate attributed to ...         353.5
Age-standardized mortality rate attributed to n...         492.3
Child malnutrition, stunting (moderate or sever...           3.5
Current health expenditure (% of GDP)                       17.1
...                                                          ...
 Income share held by richest 10 %                          30.5
Inequality in education (%)                                  2.8
Inequality in income (%)                                    27.1
Inequality in life expectancy (%)                            6.3
Inequality-adjusted education index                        0.875

[61 rows x 1 columns]

In [7]:

values = ['n.a.', 'NaN']
USA_df = USA_df[USA_df.United_States.isin(values) == False]
USA_df

                                                   United_States
Life expectancy at birth (years)                            78.9
 Age-standardized mortality rate attributed to ...         353.5
Age-standardized mortality rate attributed to n...         492.3
Child malnutrition, stunting (moderate or sever...           3.5
Current health expenditure (% of GDP)                       17.1
...                                                          ...
Population using safely managed drinking-water ...            99
Population using safely managed sanitation serv...            90
Ratio of education and health expenditure to mi...           6.2
Research and development expenditure (% of GDP)              2.8
Rural population with access to electricity (%)            100.0

[140 rows x 1 columns]

In [8]:
USA_df = USA_df.drop(['Child marriage, women married by age 18 (% of women ages 20–24 who are married or in union)\n','n.a.'])
USA_df

                                                   United_States
Life expectancy at birth (years)                            78.9
 Age-standardized mortality rate attributed to ...         353.5
Age-standardized mortality rate attributed to n...         492.3
Child malnutrition, stunting (moderate or sever...           3.5
Current health expenditure (% of GDP)                       17.1
...                                                          ...
Population using safely managed drinking-water ...            99
Population using safely managed sanitation serv...            90
Ratio of education and health expenditure to mi...           6.2
Research and development expenditure (% of GDP)              2.8
Rural population with access to electricity (%)            100.0

[138 rows x 1 columns]

In [9]:
USA_df.values

array([['78.9'],
       ['353.5'],
       ['492.3'],
       ['3.5'],
       ['17.1'],
       ['3'],
       ['10'],
       ['81.4'],
       ['76.3'],
       ['0.906'],
       ['82'],
       ['5.6'],
       ['139'],
       ['6.5'],
       ['3.0'],
       ['16.3'],
       ['0.900'],
       ['16.9'],
       ['15.7'],
       ['5.0'],
       ['73'],
       ['102'],
       ['99'],
       ['88'],
       ['13.4'],
       ['13.5'],
       ['13.4'],
       ['96.0'],
       ['96.1'],
       ['96.0'],
       ['478'],
       ['505'],
       ['502'],
       ['14'],
       ['63,826'],
       ['50,590'],
       ['77,338'],
       ['62,683'],
       ['20,575.0'],
       ['20.7'],
       ['0.976'],
       ['58.6'],
       ['0.808'],
       ['12.1'],
       ['41.4'],
       ['9.4'],
       ['15.4'],
       ['20.5'],
       ['30.5'],
       ['2.8'],
       ['27.1'],
       ['6.3'],
       ['0.875'],
       ['0.711'],
       ['0.848'],
       ['12.7'],
       ['0.994'],
       ['19.9'],
       ['75.9'],
       ['40.9'],
       ['0.204'],
       ['0.922'],
       ['0.928'],
       ['19'],
       ['99.1'],
       ['46.3'],
       ['34.0'],
       ['66.0'],
       ['10.4'],
       ['28.44'],
       ['23.7'],
       ['0.97'],
       ['9.0'],
       ['92.7'],
       ['0.76'],
       ['1.0'],
       ['59.8'],
       ['1.3'],
       ['78.9'],
       ['62.0'],
       ['56.1'],
       ['68.2'],
       ['100.0'],
       ['3.7'],
       ['8.5'],
       ['3.8'],
       ['13.8'],
       ['5.0'],
       ['100'],
       ['51'],
       ['663'],
       ['0.3'],
       ['6.4'],
       ['21.1'],
       ['26.4'],
       ['1.5'],
       ['-1.4'],
       ['0.03'],
       ['87.3'],
       ['79,746'],
       ['4.7'],
       ['74.9'],
       ['123.7'],
       ['2.9'],
       ['16.6'],
       ['0.27'],
       ['20.3'],
       ['33.9'],
       ['2.7'],
       ['82.4'],
       ['14.5'],
       ['13'],
       ['0.2'],
       ['0.4'],
       ['1.2'],
       ['0.833'],
       ['72.6'],
       ['25.4'],
       ['349.6'],
       ['38.3'],
       ['24.8'],
       ['214.7'],
       ['53.3'],
       ['19.6'],
       ['1.05'],
       ['82.5'],
       ['28.4'],
       ['96.5'],
       ['5.6'],
       ['-0.3'],
       ['0.099'],
       ['21.0'],
       ['1.3'],
       ['99'],
       ['90'],
       ['6.2'],
       ['2.8'],
       ['100.0']], dtype=object)

In [10]:
USA_df.isna()

                                                    United_States
Life expectancy at birth (years)                            False
 Age-standardized mortality rate attributed to ...          False
Age-standardized mortality rate attributed to n...          False
Child malnutrition, stunting (moderate or sever...          False
Current health expenditure (% of GDP)                       False
...                                                           ...
Population using safely managed drinking-water ...          False
Population using safely managed sanitation serv...          False
Ratio of education and health expenditure to mi...          False
Research and development expenditure (% of GDP)             False
Rural population with access to electricity (%)             False

[138 rows x 1 columns]

In [11]:
file = pd.read_excel("state_gdp.xlsx", sheet_name= "Table 3")
state_gdp_df = pd.DataFrame(file)
state_gdp_df

,"Table 3. Current-Dollar Gross Domestic Product, by State and Region, 2020:Q1–2021:Q4",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,Millions of dollars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Percent of the U.S.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Seasonally adjusted at annual rates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2020,NaN,NaN,NaN,2021,NaN,NaN,NaN,2020,NaN,NaN,NaN,2021,NaN,NaN,NaN
3,NaN,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4p,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4p
4,United States,21481367,19477444,21138574,21477597,22038226,22740959,23202344,24002815,100,100,100,100,100,100,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Overseas activity 1/,133566,132517,132066,136663,138201,142125,146180,149812,0.6,0.7,0.6,0.6,0.6,0.6,0.6,0.6
66,1. Economic activity taking place outside the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,p Preliminary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Source. U.S. Bureau of Economic Analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
state_gdp_df = state_gdp_df.drop([0,1,2,3,64,65,66,67,68])
state_gdp_df

,"Table 3. Current-Dollar Gross Domestic Product, by State and Region, 2020:Q1–2021:Q4",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
4,United States,21481367,19477444,21138574,21477597,22038226,22740959,23202344,24002815,100,100,100,100,100,100,100,100
5,New England,1142537,1034455,1119585,1142558,1159111,1198528,1219540,1260502,5.3,5.3,5.3,5.3,5.3,5.3,5.3,5.3
6,Connecticut,286287,257812,278870,282722,285112,293595,298612,308671,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3
7,Maine,70099,64704,70256,72027,73174,75214,76664,79177,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
8,Massachusetts,600436,544140,586020,599311,610700,629570,642038,663750,2.8,2.8,2.8,2.8,2.8,2.8,2.8,2.8
9,New Hampshire,89251,80750,88890,91593,92753,98746,99030,102439,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
10,Rhode Island,61776,56289,61653,62508,62340,65700,66894,68823,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
11,Vermont,34688,30758,33897,34397,35032,35703,36302,37644,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
12,Mideast,3884793,3500191,3777249,3822776,3904216,3994777,4064802,4181856,18.1,18,17.9,17.8,17.7,17.6,17.5,17.4
13,Delaware,77074,71818,76815,77439,77392,79728,81546,84206,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
14,District of Columbia,147340,139171,144287,147421,147830,150577,153168,156457,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7
15,Maryland,422760,387607,415082,417251,430607,431319,439028,451986,2,2,2,1.9,2,1.9,1.9,1.9
16,New Jersey,646387,571006,624873,632051,649336,661895,677006,700119,3,2.9,3,2.9,2.9,2.9,2.9,2.9
17,New York,1789195,1618038,1736426,1755377,1791204,1842363,1867929,1914207,8.3,8.3,8.2,8.2,8.1,8.1,8.1,8
18,Pennsylvania,802036,712551,779767,793237,807846,828896,846123,874881,3.7,3.7,3.7,3.7,3.7,3.6,3.6,3.6
19,Great Lakes,2842449,2558828,2809540,2845578,2916245,3000101,3052819,3148758,13.2,13.1,13.3,13.2,13.2,13.2,13.2,13.1
20,Illinois,885630,804348,866286,877203,906798,927452,945654,973486,4.1,4.1,4.1,4.1,4.1,4.1,4.1,4.1
21,Indiana,384065,344388,383794,389099,403694,415923,423729,438012,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
22,Michigan,532286,467167,528249,532778,541145,566009,574150,592349,2.5,2.4,2.5,2.5,2.5,2.5,2.5,2.5
23,Ohio,696308,627253,688816,697868,710999,728398,741400,765003,3.2,3.2,3.3,3.2,3.2,3.2,3.2,3.2
24,Wisconsin,344159,315671,342396,348629,353610,362319,367887,379909,1.6,1.6,1.6,1.6,1.6,1.6,1.6,1.6
25,Plains,1343533,1229935,1329924,1359002,1400121,1449479,1476900,1509813,6.3,6.3,6.3,6.3,6.4,6.4,6.4,6.3
26,Iowa,196419,181989,196938,201724,210045,219941,223685,225696,0.9,0.9,0.9,0.9,1,1,1,0.9
27,Kansas,178882,162994,177873,180818,185475,191170,194278,198291,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8
28,Minnesota,383709,351218,376935,383095,392457,408961,417194,429391,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
29,Missouri,335481,308248,333640,340099,347677,356070,362956,373105,1.6,1.6,1.6,1.6,1.6,1.6,1.6,1.6
30,Nebraska,134756,123846,134929,140226,145825,149355,152222,154149,0.6,0.6,0.6,0.7,0.7,0.7,0.7,0.6
31,North Dakota,58494,50509,54520,55893,59703,62890,64583,66372,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
32,South Dakota,55792,51129,55088,57148,58939,61094,61980,62809,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
33,Southeast,4581243,4174675,4546906,4608412,4727565,4880553,4985228,5161681,21.3,21.4,21.5,21.5,21.5,21.5,21.5,21.5
34,Alabama,231793,210576,231581,233636,238126,243787,248991,257465,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1
35,Arkansas,132472,122959,133037,134535,138771,143004,145924,150483,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6
36,Florida,1127295,1034694,1126332,1135822,1163342,1213461,1242300,1286086,5.2,5.3,5.3,5.3,5.3,5.3,5.4,5.4
37,Georgia,637690,585216,630252,637354,653600,675620,690040,713948,3,3,3,3,3,3,3,3
38,Kentucky,217971,195399,217253,219536,225701,231511,236301,244480,1,1,1,1,1,1,1,1
39,Louisiana,247300,219516,236762,238171,243641,253298,257161,267126,1.2,1.1,1.1,1.1,1.1,1.1,1.1,1.1
40,Mississippi,116407,104988,115950,118037,120445,123758,126264,129974,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
41,North Carolina,603140,549900,598498,607778,628106,646904,660327,684607,2.8,2.8,2.8,2.8,2.9,2.8,2.8,2.9
42,South Carolina,247226,227781,250740,253781,259691,266774,272097,281754,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2
43,Tennessee,382646,335712,375477,384462,400792,411983,421352,439050,1.8,1.7,1.8,1.8,1.8,1.8,1.8,1.8
44,Virginia,559123,519052,554367,565602,572428,584197,596025,614754,2.6,2.7,2.6,2.6,2.6,2.6,2.6,2.6
45,West Virginia,78180,68882,76659,79699,82923,86257,88446,91953,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
46,Southwest,2513988,2268609,2454364,2506381,2574602,2665932,2740579,2867642,11.7,11.6,11.6,11.7,11.7,11.7,11.8,11.9
47,Arizona,375700,351318,378850,389007,393599,405789,415561,429819,1.7,1.8,1.8,1.8,1.8,1.8,1.8,1.8
48,New Mexico,103269,91388,98586,100645,104315,107115,109603,114680,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
49,Oklahoma,196918,174514,189111,191683,196400,203273,208765,218564,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9
50,Texas,1838100,1651389,1787816,1825045,1880288,1949756,2006650,2104579,8.6,8.5,8.5,8.5,8.5,8.6,8.6,8.8
51,Rocky Mountain,767605,704324,759111,776161,800790,827699,845607,876006,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6
52,Colorado,395421,358716,385075,391126,402761,417624,426477,440903,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
53,Idaho,84482,77636,85470,87698,90552,93410,94850,98455,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
54,Montana,51948,47992,52341,53755,56453,58755,60020,61983,0.2,0.2,0.2,0.3,0.3,0.3,0.3,0.3
55,Utah,196920,186766,200044,206518,211721,217148,222157,230342,0.9,1,0.9,1,1,1,1,1
56,Wyoming,38834,33215,36181,37064,39303,40761,42102,44323,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
57,Far West,4271657,3873913,4209832,4280066,4417373,4581767,4670691,4846747,19.9,19.9,19.9,19.9,20,20.1,20.1,20.2
58,Alaska,53103,45945,48877,51355,52164,54056,55677,57983,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
59,California,3083611,2801947,3042208,3100985,3207139,3321704,3384335,3513348,14.4,14.4,14.4,14.4,14.6,14.6,14.6,14.6
60,Hawaii,90324,77670,81035,82509,84183,89170,91947,94937,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
61,Nevada,184994,151094,172158,175529,180973,190799,195777,204306,0.9,0.8,0.8,0.8,0.8,0.8,0.8,0.9
62,Oregon,250597,228542,246357,249611,256567,262917,268864,279424,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2
63,Washington,609026,568716,619197,620076,636347,663121,674091,696748,2.8,2.9,2.9,2.9,2.9,2.9,2.9,2.9

In [13]:
state_gdp_df.columns = ['State', 'Q1_2020', 'Q2_2020', 'Q3_2020', 'Q4_2020', 'Q1_2021', 'Q2_2021', 'Q3_2021', 'Q4_2021', 'per_Q1_2020', 'per_Q2_2020', 'per_Q3_2020', 'per_Q4_2020', 'per_Q1_2021', 'per_Q2_2021', 'per_Q3_2021', 'per_Q4_2021']
state_gdp_df

,State,Q1_2020,Q2_2020,Q3_2020,Q4_2020,Q1_2021,Q2_2021,Q3_2021,Q4_2021,per_Q1_2020,per_Q2_2020,per_Q3_2020,per_Q4_2020,per_Q1_2021,per_Q2_2021,per_Q3_2021,per_Q4_2021
4,United States,21481367,19477444,21138574,21477597,22038226,22740959,23202344,24002815,100,100,100,100,100,100,100,100
5,New England,1142537,1034455,1119585,1142558,1159111,1198528,1219540,1260502,5.3,5.3,5.3,5.3,5.3,5.3,5.3,5.3
6,Connecticut,286287,257812,278870,282722,285112,293595,298612,308671,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3
7,Maine,70099,64704,70256,72027,73174,75214,76664,79177,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
8,Massachusetts,600436,544140,586020,599311,610700,629570,642038,663750,2.8,2.8,2.8,2.8,2.8,2.8,2.8,2.8
9,New Hampshire,89251,80750,88890,91593,92753,98746,99030,102439,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
10,Rhode Island,61776,56289,61653,62508,62340,65700,66894,68823,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
11,Vermont,34688,30758,33897,34397,35032,35703,36302,37644,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
12,Mideast,3884793,3500191,3777249,3822776,3904216,3994777,4064802,4181856,18.1,18,17.9,17.8,17.7,17.6,17.5,17.4
13,Delaware,77074,71818,76815,77439,77392,79728,81546,84206,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
14,District of Columbia,147340,139171,144287,147421,147830,150577,153168,156457,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7
15,Maryland,422760,387607,415082,417251,430607,431319,439028,451986,2,2,2,1.9,2,1.9,1.9,1.9
16,New Jersey,646387,571006,624873,632051,649336,661895,677006,700119,3,2.9,3,2.9,2.9,2.9,2.9,2.9
17,New York,1789195,1618038,1736426,1755377,1791204,1842363,1867929,1914207,8.3,8.3,8.2,8.2,8.1,8.1,8.1,8
18,Pennsylvania,802036,712551,779767,793237,807846,828896,846123,874881,3.7,3.7,3.7,3.7,3.7,3.6,3.6,3.6
19,Great Lakes,2842449,2558828,2809540,2845578,2916245,3000101,3052819,3148758,13.2,13.1,13.3,13.2,13.2,13.2,13.2,13.1
20,Illinois,885630,804348,866286,877203,906798,927452,945654,973486,4.1,4.1,4.1,4.1,4.1,4.1,4.1,4.1
21,Indiana,384065,344388,383794,389099,403694,415923,423729,438012,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
22,Michigan,532286,467167,528249,532778,541145,566009,574150,592349,2.5,2.4,2.5,2.5,2.5,2.5,2.5,2.5
23,Ohio,696308,627253,688816,697868,710999,728398,741400,765003,3.2,3.2,3.3,3.2,3.2,3.2,3.2,3.2
24,Wisconsin,344159,315671,342396,348629,353610,362319,367887,379909,1.6,1.6,1.6,1.6,1.6,1.6,1.6,1.6
25,Plains,1343533,1229935,1329924,1359002,1400121,1449479,1476900,1509813,6.3,6.3,6.3,6.3,6.4,6.4,6.4,6.3
26,Iowa,196419,181989,196938,201724,210045,219941,223685,225696,0.9,0.9,0.9,0.9,1,1,1,0.9
27,Kansas,178882,162994,177873,180818,185475,191170,194278,198291,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8
28,Minnesota,383709,351218,376935,383095,392457,408961,417194,429391,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
29,Missouri,335481,308248,333640,340099,347677,356070,362956,373105,1.6,1.6,1.6,1.6,1.6,1.6,1.6,1.6
30,Nebraska,134756,123846,134929,140226,145825,149355,152222,154149,0.6,0.6,0.6,0.7,0.7,0.7,0.7,0.6
31,North Dakota,58494,50509,54520,55893,59703,62890,64583,66372,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
32,South Dakota,55792,51129,55088,57148,58939,61094,61980,62809,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
33,Southeast,4581243,4174675,4546906,4608412,4727565,4880553,4985228,5161681,21.3,21.4,21.5,21.5,21.5,21.5,21.5,21.5
34,Alabama,231793,210576,231581,233636,238126,243787,248991,257465,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1
35,Arkansas,132472,122959,133037,134535,138771,143004,145924,150483,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6
36,Florida,1127295,1034694,1126332,1135822,1163342,1213461,1242300,1286086,5.2,5.3,5.3,5.3,5.3,5.3,5.4,5.4
37,Georgia,637690,585216,630252,637354,653600,675620,690040,713948,3,3,3,3,3,3,3,3
38,Kentucky,217971,195399,217253,219536,225701,231511,236301,244480,1,1,1,1,1,1,1,1
39,Louisiana,247300,219516,236762,238171,243641,253298,257161,267126,1.2,1.1,1.1,1.1,1.1,1.1,1.1,1.1
40,Mississippi,116407,104988,115950,118037,120445,123758,126264,129974,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
41,North Carolina,603140,549900,598498,607778,628106,646904,660327,684607,2.8,2.8,2.8,2.8,2.9,2.8,2.8,2.9
42,South Carolina,247226,227781,250740,253781,259691,266774,272097,281754,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2
43,Tennessee,382646,335712,375477,384462,400792,411983,421352,439050,1.8,1.7,1.8,1.8,1.8,1.8,1.8,1.8
44,Virginia,559123,519052,554367,565602,572428,584197,596025,614754,2.6,2.7,2.6,2.6,2.6,2.6,2.6,2.6
45,West Virginia,78180,68882,76659,79699,82923,86257,88446,91953,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
46,Southwest,2513988,2268609,2454364,2506381,2574602,2665932,2740579,2867642,11.7,11.6,11.6,11.7,11.7,11.7,11.8,11.9
47,Arizona,375700,351318,378850,389007,393599,405789,415561,429819,1.7,1.8,1.8,1.8,1.8,1.8,1.8,1.8
48,New Mexico,103269,91388,98586,100645,104315,107115,109603,114680,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
49,Oklahoma,196918,174514,189111,191683,196400,203273,208765,218564,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9
50,Texas,1838100,1651389,1787816,1825045,1880288,1949756,2006650,2104579,8.6,8.5,8.5,8.5,8.5,8.6,8.6,8.8
51,Rocky Mountain,767605,704324,759111,776161,800790,827699,845607,876006,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6
52,Colorado,395421,358716,385075,391126,402761,417624,426477,440903,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
53,Idaho,84482,77636,85470,87698,90552,93410,94850,98455,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
54,Montana,51948,47992,52341,53755,56453,58755,60020,61983,0.2,0.2,0.2,0.3,0.3,0.3,0.3,0.3
55,Utah,196920,186766,200044,206518,211721,217148,222157,230342,0.9,1,0.9,1,1,1,1,1
56,Wyoming,38834,33215,36181,37064,39303,40761,42102,44323,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
57,Far West,4271657,3873913,4209832,4280066,4417373,4581767,4670691,4846747,19.9,19.9,19.9,19.9,20,20.1,20.1,20.2
58,Alaska,53103,45945,48877,51355,52164,54056,55677,57983,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
59,California,3083611,2801947,3042208,3100985,3207139,3321704,3384335,3513348,14.4,14.4,14.4,14.4,14.6,14.6,14.6,14.6
60,Hawaii,90324,77670,81035,82509,84183,89170,91947,94937,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
61,Nevada,184994,151094,172158,175529,180973,190799,195777,204306,0.9,0.8,0.8,0.8,0.8,0.8,0.8,0.9
62,Oregon,250597,228542,246357,249611,256567,262917,268864,279424,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2
63,Washington,609026,568716,619197,620076,636347,663121,674091,696748,2.8,2.9,2.9,2.9,2.9,2.9,2.9,2.9